language: perl
sudo: false

addons:
  apt:
    packages:
      - libhunspell-dev

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | grep -v Text::Hunspell | cpanm -n
  - cpanm -v $TEXT_HUNSPELL

perl:
  - "5.20"
  - "5.22"

script:
  - dzil test -v

env:
  - TEXT_HUNSPELL=Text::Hunspell::FFI
  - TEXT_HUNSPELL=Text::Hunspell
